### PR TITLE
Add moderation flow to PEER

### PR DESCRIPTION
**Pull request by jkakavas**
Hello, 

We are evaluating the use of PEER for [GRNET federation](http://aai.grnet.gr/) and we had the need for a moderation flow where the changes in the metadata of participating entities need to be moderated and approved by someone in the federation administration. The moderation flow implements the use cases where the federation administrators want/are required to have control over the entities metadata (for policy enforcement, quality assurance, etc.). When moderation is enabled in PEER, all changes in the metadata entities made in PEER have to be reviewed and approved by a moderator before they are reflected to the actual metadata XML document that is stored in disk under version control. The assumption is that the XML files are considered the "published" version of the metadata and are used for metadata aggregation etc.

We have attempted to make the changes as less intrusive as possible and as close to the original code architecture and conventions. The moderation flow is enabled with a use of a boolean flag in settings.py and with it set to false, PEER functionality and behavior is exactly the same as with the original release. 

We are now sharing the changes that we made to peer with the rest of the community in order to get insights/comments and if the modifications and extended functionality is useful for others, we would welcome the incorporation of the modifications in PEER by merging this pull request. 

For a detailed functional and technical design document describing the moderation flow and an overview of the modifications made, please see : https://github.com/jkakavas/peer/blob/master/doc/moderation_flow.rst

### CODE REVIEW

**Comment by enriquepablo** [comment]
Awesome. We are testing this and will get back to you in a couple of days.

**Comment by enriquepablo** [comment]
Hi Yiannis, we were going to test your code but the code for the db migration seems to be missing...

**Comment by jkakavas** [comment]
Hi Enrique, sorry for that, somehow missed committing the migrations. I added them now

**Comment by enriquepablo** [comment]
Perfect, thanks, we are deploying and testing :)

**Comment by jkakavas** [comment]
Hello, 

Since I start to see some movement in the repo with new owners and members, are there any plans on evaluating this pull request ?

**Comment by enriquepablo** [comment]
Hi,

Yes, the plan is to evaluate and merge in the next couple of days.

2015-06-09 13:22 GMT+02:00 Ioannis Kakavas <notifications@github.com>:

> Hello,
>
> Since I start to see some movement in the repo with new owners and
> members, are there any plans on evaluating this pull request ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Emergya/peer/pull/57#issuecomment-110321902>.
>



-- 
Enrique Pérez Arnaud
enrique@cazalla.net

**Pull request merged**
